# Generated by Django 4.2.28 on 2026-08-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('nom_entreprise', models.CharField(max_length=255, unique=True, verbose_name='Entreprise')),
                ('contact', models.CharField(blank=True, max_length=150, verbose_name='Contact')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse e-mail')),
                ('compte_identifiant', models.CharField(blank=True, db_index=True, help_text="Identifiant de connexion du contact, s'il consulte son planning.", max_length=150, verbose_name='Compte client')),
                ('actif', models.BooleanField(default=True, verbose_name='Client actif')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client_planning',
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.CreateModel(
            name='IdeeContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('type_contenu', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image'), ('TEXTE', 'Texte')], max_length=6, verbose_name='Type')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Idee de contenu',
                'verbose_name_plural': 'Idees de contenu',
                'db_table': 'idee_contenu',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Tournage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('date', models.DateField(verbose_name='Date')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REALISE', 'Realise'), ('ANNULE', 'Annule'), ('NON_REALISE', 'Non realise'), ('REPROGRAMME', 'Reprogramme')], default='EN_ATTENTE', max_length=12, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('motif_statut', models.TextField(blank=True, help_text="Pourquoi cette echeance n'a pas ete tenue.", verbose_name='Motif')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournages', to='planning.client')),
                ('idees', models.ManyToManyField(blank=True, related_name='tournages', to='planning.ideecontenu', verbose_name='Idees traitees')),
            ],
            options={
                'verbose_name': 'Tournage',
                'verbose_name_plural': 'Tournages',
                'db_table': 'tournage',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReglePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10, verbose_name='Jour')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='planning.client')),
            ],
            options={
                'verbose_name': 'Regle de publication',
                'verbose_name_plural': 'Regles de publication',
                'db_table': 'regle_publication',
                'ordering': ['client__nom_entreprise', 'jour'],
            },
        ),
        migrations.CreateModel(
            name='RapportClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Annee')),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu')),
                ('indicateurs', models.JSONField(blank=True, default=dict, verbose_name='Indicateurs')),
                ('telechargements', models.IntegerField(default=0, verbose_name='Telechargements')),
                ('genere_par_identifiant', models.CharField(blank=True, max_length=150, verbose_name='Genere par')),
                ('genere_par_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='planning.client')),
            ],
            options={
                'verbose_name': 'Rapport client',
                'verbose_name_plural': 'Rapports clients',
                'db_table': 'rapport_client',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('date', models.DateField(verbose_name='Date')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REALISE', 'Realise'), ('ANNULE', 'Annule'), ('NON_REALISE', 'Non realise'), ('REPROGRAMME', 'Reprogramme')], default='EN_ATTENTE', max_length=12, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('motif_statut', models.TextField(blank=True, help_text="Pourquoi cette echeance n'a pas ete tenue.", verbose_name='Motif')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='planning.client')),
                ('idee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='planning.ideecontenu')),
                ('tournage', models.ForeignKey(blank=True, help_text="Facultatif : un texte ou une image d'archive n'en a pas.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='planning.tournage')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'db_table': 'publication',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='tournage',
            index=models.Index(fields=['client', 'date'], name='tournage_client__bbe8a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='reglepublication',
            constraint=models.UniqueConstraint(fields=('client', 'jour'), name='une_regle_par_client_et_jour'),
        ),
        migrations.AddConstraint(
            model_name='rapportclient',
            constraint=models.UniqueConstraint(fields=('client', 'mois', 'annee'), name='un_rapport_par_client_et_mois'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['client', 'date'], name='publication_client__bf4e62_idx'),
        ),
    ]
