# Generated by Django 4.2.28 on 2026-08-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheseMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('mois', models.DateField(help_text='Premier jour du mois concerne.', verbose_name='Mois')),
                ('application', models.CharField(help_text='rh, finance, bdm...', max_length=32, verbose_name='Application')),
                ('indicateurs', models.JSONField(default=dict, verbose_name='Indicateurs')),
                ('construite_par', models.CharField(blank=True, max_length=150, verbose_name='Construite par')),
            ],
            options={
                'verbose_name': 'Synthese mensuelle',
                'verbose_name_plural': 'Syntheses mensuelles',
                'db_table': 'synthese_mensuelle',
                'ordering': ['-mois', 'application'],
            },
        ),
        migrations.AddConstraint(
            model_name='synthesemensuelle',
            constraint=models.UniqueConstraint(fields=('mois', 'application'), name='une_synthese_par_mois_et_application'),
        ),
    ]
