# Generated by Django 4.2.28 on 2026-08-24 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiseAJourJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('agent_identifiant', models.CharField(blank=True, max_length=150, verbose_name='Saisi par')),
                ('agent_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('date_rapport', models.DateField(verbose_name='Date')),
                ('avancement', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avancement')),
                ('statut', models.CharField(choices=[('NON_DEMARRE', 'Non demarre'), ('EN_COURS', 'En cours'), ('TERMINE', 'Termine'), ('ANNULE', 'Annule')], default='NON_DEMARRE', max_length=12, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Mise a jour journaliere',
                'verbose_name_plural': 'Mises a jour journalieres',
                'db_table': 'mise_a_jour_journaliere',
                'ordering': ['-date_rapport', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('masquee_partenaire', models.BooleanField(default=False, verbose_name='Masquee au partenaire')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
                'db_table': 'phase',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('client', models.CharField(blank=True, max_length=255, verbose_name='Client')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Debut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifie'), ('EN_COURS', 'En cours'), ('TERMINE', 'Termine'), ('SUSPENDU', 'Suspendu')], default='PLANIFIE', max_length=12, verbose_name='Statut')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'db_table': 'projet',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SousPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('masquee_partenaire', models.BooleanField(default=False, verbose_name='Masquee au partenaire')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_phases', to='chantiers.phase')),
            ],
            options={
                'verbose_name': 'Sous-phase',
                'verbose_name_plural': 'Sous-phases',
                'db_table': 'sous_phase',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('activite', models.CharField(max_length=500, verbose_name='Activite')),
                ('jour_debut', models.IntegerField(default=1, help_text='Compte a partir du demarrage du projet.', verbose_name='Jour de debut')),
                ('duree_jours', models.IntegerField(default=1, verbose_name='Duree (jours)')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('masquee_partenaire', models.BooleanField(default=False, verbose_name='Masquee au partenaire')),
                ('sous_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='chantiers.sousphase')),
            ],
            options={
                'verbose_name': 'Tache',
                'verbose_name_plural': 'Taches',
                'db_table': 'tache',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('agent_identifiant', models.CharField(blank=True, max_length=150, verbose_name='Redige par')),
                ('agent_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('date_rapport', models.DateField(verbose_name='Date')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature')),
                ('meteo', models.CharField(blank=True, max_length=100, verbose_name='Meteo')),
                ('avancement_global', models.IntegerField(default=0, verbose_name='Avancement global')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='chantiers.projet')),
            ],
            options={
                'verbose_name': 'Rapport journalier',
                'verbose_name_plural': 'Rapports journaliers',
                'db_table': 'rapport_journalier',
                'ordering': ['-date_rapport'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('agent_identifiant', models.CharField(blank=True, max_length=150, verbose_name='Prise par')),
                ('agent_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('categorie', models.CharField(choices=[('AVANT', 'Avant'), ('PENDANT', 'Pendant'), ('APRES', 'Apres'), ('SECURITE', 'Securite'), ('QUALITE', 'Qualite')], max_length=10, verbose_name='Categorie')),
                ('fichier', models.FileField(upload_to='chantiers/photos/%Y/%m/', verbose_name='Fichier')),
                ('nom_origine', models.CharField(blank=True, max_length=255, verbose_name="Nom d'origine")),
                ('legende', models.CharField(blank=True, max_length=255, verbose_name='Legende')),
                ('prise_le', models.DateField(blank=True, null=True, verbose_name='Prise le')),
                ('taille', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='chantiers.projet')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'photo_chantier',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='phase',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='chantiers.projet'),
        ),
        migrations.CreateModel(
            name='NoteAvancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('agent_identifiant', models.CharField(blank=True, max_length=150, verbose_name='Redigee par')),
                ('agent_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('avancement', models.IntegerField(default=0, verbose_name='Avancement')),
                ('avancement_precedent', models.IntegerField(default=0, verbose_name='Avancement precedent')),
                ('corps', models.TextField(blank=True, verbose_name='Note')),
                ('mise_a_jour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='chantiers.miseajourjournaliere')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_avancement', to='chantiers.tache')),
            ],
            options={
                'verbose_name': "Note d'avancement",
                'verbose_name_plural': "Notes d'avancement",
                'db_table': 'note_avancement',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='miseajourjournaliere',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mises_a_jour', to='chantiers.tache'),
        ),
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('agent_identifiant', models.CharField(blank=True, max_length=150, verbose_name='Agent')),
                ('agent_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('objet_type', models.CharField(blank=True, max_length=100, verbose_name="Type d'objet")),
                ('objet_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Objet')),
                ('projet_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': "Journal d'activite",
                'verbose_name_plural': "Journal d'activite",
                'db_table': 'journal_activite_chantier',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['projet_id', '-cree_le'], name='journal_act_projet__bf1073_idx')],
            },
        ),
        migrations.CreateModel(
            name='AffectationProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('agent_identifiant', models.CharField(db_index=True, max_length=150, verbose_name='Agent')),
                ('agent_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('affecte_par', models.CharField(blank=True, max_length=150, verbose_name='Affecte par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='chantiers.projet')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'db_table': 'affectation_projet',
                'ordering': ['agent_nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='rapportjournalier',
            constraint=models.UniqueConstraint(fields=('projet', 'date_rapport'), name='un_rapport_par_projet_et_jour'),
        ),
        migrations.AddConstraint(
            model_name='miseajourjournaliere',
            constraint=models.UniqueConstraint(fields=('tache', 'date_rapport'), name='une_saisie_par_tache_et_jour'),
        ),
        migrations.AddConstraint(
            model_name='affectationprojet',
            constraint=models.UniqueConstraint(fields=('projet', 'agent_identifiant'), name='une_affectation_par_agent_et_projet'),
        ),
    ]
