# Generated by Django 4.2.28 on 2026-08-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('identifiant', models.CharField(help_text='Le meme que dans identity : e-mail professionnel le plus souvent.', max_length=150, unique=True, verbose_name='Identifiant de connexion')),
                ('compte_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Compte identity')),
                ('matricule', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Matricule')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prenom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse professionnelle')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Telephone')),
                ('poste', models.CharField(blank=True, max_length=120, verbose_name='Poste')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('PRESTATAIRE', 'Prestataire')], default='CDI', max_length=15, verbose_name='Type de contrat')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('motif_sortie', models.CharField(blank=True, choices=[('DEMISSION', 'Demission'), ('LICENCIEMENT', 'Licenciement'), ('FIN_CONTRAT', 'Fin de contrat'), ('RETRAITE', 'Retraite'), ('AUTRE', 'Autre')], max_length=15, verbose_name='Motif de sortie')),
                ('actif', models.BooleanField(default=True, verbose_name='Agent en poste')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agent',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('actif', models.BooleanField(default=True, verbose_name='Departement actif')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to='organisation.agent', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
                'db_table': 'departement',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='organisation.departement', verbose_name='Departement'),
        ),
        migrations.AddField(
            model_name='agent',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Designe le premier valideur des demandes de cet agent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='organisation.agent', verbose_name='Responsable direct'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['actif', 'departement'], name='agent_actif_27d412_idx'),
        ),
    ]
